name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull submodules
      run: git submodule update --init --recursive

    - name: Build the Docker image
      run: docker build . --target base --tag ghcr.io/m4s-dev/moodle-docker:${GITHUB_SHA}

    - name: Build static image
      run: docker build . --target nginx --tag ghcr.io/m4s-dev/moodle-docker:nginx-${GITHUB_SHA}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: m4sbot
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Github Container Registry
      run: |
          docker push ghcr.io/m4s-dev/moodle-docker:${GITHUB_SHA}
          docker push ghcr.io/m4s-dev/moodle-docker:nginx-${GITHUB_SHA}
